---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: expressjs-k8s
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.3
spec:
  chart:
    repository: https://docker.io
    name: polskikiel/alpine
    version: 0.1.0
  values:
    ingress:
      enabled: false
    image: alexellis2/service:0.3.7
